version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_dashfinances
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=dashpg
      - POSTGRES_PASSWORD=dashpg
      - POSTGRES_DB=dashfinances
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: dashfinances
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local