CREATE DATABASE dashfinances;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS finances (
  id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  name VARCHAR NOT NULL,
  category VARCHAR NOT NULL,
  amount FLOAT NOT NULL,
  created DATE NOT NULL,
  user_id UUID,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);